elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"
  volumes:
  - /data:/usr/share/elasticsearch/data
kibana:
  image: kibana
  ports:
   - "5601:5601"
  links:
   - elasticsearch
logstash:
  build: logstash
  command: logstash --config /conf
  ports:
   - "5000:5000"
  links:
   - elasticsearch